[tools]
python = "3.12.3"

[env]
_.python.venv = ".venv"

[tasks]
setup = ['uv venv', 'uv pip install .']
format = "python -m ruff format tsp"
lint = "python -m ruff check --fix tsp"
test = "python -m unittest discover -s tsp -p '*_test.py'"

[tasks.check]
depends = ["format", "lint", "test"]
