name: commit

on:
  push:

jobs:
  commit-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
          cache: pip
      - run: pip install uv
      - run: uv venv
      - run: uv pip install .
      - run: .venv/bin/python -m ruff format --check tsp
      - run: .venv/bin/python -m ruff check tsp
      - run: .venv/bin/python -m unittest discover -s tsp -p '*_test.py'
